# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AlertBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class AlertBox(QtWidgets.QDialog):
    def __init__(self, txt, parent=None):
        super().__init__(parent)
        self.text = txt
        AlertBox = self
        AlertBox.setObjectName("AlertBox")
        AlertBox.resize(262, 189)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICONOI.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AlertBox.setWindowIcon(icon)
        AlertBox.setAutoFillBackground(False)
        AlertBox.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(130, 35, 233, 255), stop:1 rgba(162, 0, 0, 255));")
        self.centralwidget = QtWidgets.QWidget(AlertBox)
        self.centralwidget.setObjectName("centralwidget")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(60, 110, 131, 41))
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setStyleSheet("background-color: rgb(249, 167, 25);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnNext.setObjectName("btnNext")
        self.btnNext.clicked.connect(self.returnMain)

        self.eAlerta = QtWidgets.QLabel(self.centralwidget)
        self.eAlerta.setGeometry(QtCore.QRect(20, 20, 221, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eAlerta.setFont(font)
        self.eAlerta.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"color: rgb(213, 0, 0);\n"
"border-radius:10px;")
        self.eAlerta.setObjectName("eAlerta")
        self.eAlerta.setText(self.text)
        # AlertBox.setCentralWidget(self.centralwidget)

        self.retranslateUi(AlertBox)
        
        print(self.text)
        # QtCore.QMetaObject.connectSlotsByName(AlertBox)

    def retranslateUi(self, AlertBox):
        _translate = QtCore.QCoreApplication.translate
        AlertBox.setWindowTitle(_translate("AlertBox", "Alerta"))
        self.btnNext.setText(_translate("AlertBox", "Aceptar"))
        self.eAlerta.setText(self.text)

    def returnMain(self):
        self.hide()