# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryHome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryHome(object):
    def setupUi(self, InventoryHome):
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        InventoryHome.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InventoryHome)
        self.statusbar.setObjectName("statusbar")
        InventoryHome.setStatusBar(self.statusbar)

        self.retranslateUi(InventoryHome)
        QtCore.QMetaObject.connectSlotsByName(InventoryHome)

    


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InventoryHome = QtWidgets.QMainWindow()
    ui = Ui_InventoryHome()
    ui.setupUi(InventoryHome)
    InventoryHome.show()
    sys.exit(app.exec_())
