# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryRegis.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProducts(object):
    def setupUi(self, AddProducts):
        AddProducts.setObjectName("AddProducts")
        AddProducts.resize(659, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICONOI.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddProducts.setWindowIcon(icon)
        AddProducts.setAutoFillBackground(False)
        AddProducts.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(4,155,180, 255), stop:1 rgba(125,216,87, 255));")
        self.centralwidget = QtWidgets.QWidget(AddProducts)
        self.centralwidget.setObjectName("centralwidget")
        self.tittleInv = QtWidgets.QLabel(self.centralwidget)
        self.tittleInv.setGeometry(QtCore.QRect(150, 20, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittleInv.setFont(font)
        self.tittleInv.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"\n"
"")
        self.tittleInv.setObjectName("tittleInv")
        self.iProductInv = QtWidgets.QLineEdit(self.centralwidget)
        self.iProductInv.setGeometry(QtCore.QRect(300, 170, 181, 31))
        self.iProductInv.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iProductInv.setText("")
        self.iProductInv.setObjectName("iProductInv")
        self.eProductInv = QtWidgets.QLabel(self.centralwidget)
        self.eProductInv.setGeometry(QtCore.QRect(150, 170, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eProductInv.setFont(font)
        self.eProductInv.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eProductInv.setObjectName("eProductInv")
        self.eCantInv = QtWidgets.QLabel(self.centralwidget)
        self.eCantInv.setGeometry(QtCore.QRect(150, 250, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eCantInv.setFont(font)
        self.eCantInv.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eCantInv.setObjectName("eCantInv")
        self.eRefInv = QtWidgets.QLabel(self.centralwidget)
        self.eRefInv.setGeometry(QtCore.QRect(150, 210, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eRefInv.setFont(font)
        self.eRefInv.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eRefInv.setObjectName("eRefInv")
        self.addProd = QtWidgets.QPushButton(self.centralwidget)
        self.addProd.setGeometry(QtCore.QRect(270, 340, 231, 41))
        self.addProd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProd.setStyleSheet("background-color: rgb(220, 110, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.addProd.setObjectName("addProd")
        self.btnBackInv = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackInv.setGeometry(QtCore.QRect(350, 390, 91, 41))
        self.btnBackInv.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBackInv.setStyleSheet("background-color: rgb(85, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnBackInv.setObjectName("btnBackInv")
        self.spinCant = QtWidgets.QSpinBox(self.centralwidget)
        self.spinCant.setGeometry(QtCore.QRect(300, 250, 181, 31))
        self.spinCant.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.spinCant.setObjectName("spinCant")
        self.tittle_2 = QtWidgets.QLabel(self.centralwidget)
        self.tittle_2.setGeometry(QtCore.QRect(210, 60, 281, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittle_2.setFont(font)
        self.tittle_2.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"\n"
"")
        self.tittle_2.setObjectName("tittle_2")
        self.iRefInv = QtWidgets.QComboBox(self.centralwidget)
        self.iRefInv.setGeometry(QtCore.QRect(300, 210, 181, 31))
        self.iRefInv.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iRefInv.setObjectName("iRefInv")
        self.prodExists = QtWidgets.QCheckBox(self.centralwidget)
        self.prodExists.setGeometry(QtCore.QRect(150, 130, 241, 21))
        self.prodExists.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 14pt \"Tw Cen MT Condensed Extra Bold\";")
        self.prodExists.setObjectName("prodExists")
        self.iUnit = QtWidgets.QLineEdit(self.centralwidget)
        self.iUnit.setGeometry(QtCore.QRect(300, 290, 181, 31))
        self.iUnit.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iUnit.setText("")
        self.iUnit.setObjectName("iUnit")
        self.eCantInv_2 = QtWidgets.QLabel(self.centralwidget)
        self.eCantInv_2.setGeometry(QtCore.QRect(150, 290, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eCantInv_2.setFont(font)
        self.eCantInv_2.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eCantInv_2.setObjectName("eCantInv_2")
        AddProducts.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddProducts)
        QtCore.QMetaObject.connectSlotsByName(AddProducts)
        AddProducts.setTabOrder(self.iProductInv, self.iRefInv)
        AddProducts.setTabOrder(self.iRefInv, self.spinCant)
        AddProducts.setTabOrder(self.spinCant, self.prodExists)
        AddProducts.setTabOrder(self.prodExists, self.addProd)
        AddProducts.setTabOrder(self.addProd, self.btnBackInv)

    def retranslateUi(self, AddProducts):
        _translate = QtCore.QCoreApplication.translate
        AddProducts.setWindowTitle(_translate("AddProducts", "Agregar Productos al Inventario"))
        self.tittleInv.setText(_translate("AddProducts", "AGREGAR PRODUCTOS"))
        self.eProductInv.setText(_translate("AddProducts", "Producto:"))
        self.eCantInv.setText(_translate("AddProducts", "Cantidad:"))
        self.eRefInv.setText(_translate("AddProducts", "Referencia:"))
        self.addProd.setText(_translate("AddProducts", "Agregar Producto"))
        self.btnBackInv.setText(_translate("AddProducts", "Atrás"))
        self.tittle_2.setText(_translate("AddProducts", "AL INVENTARIO"))
        self.prodExists.setText(_translate("AddProducts", "El producto ya existe?"))
        self.eCantInv_2.setText(_translate("AddProducts", "Precio:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProducts = QtWidgets.QMainWindow()
    ui = Ui_AddProducts()
    ui.setupUi(AddProducts)
    AddProducts.show()
    sys.exit(app.exec_())
