# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryHome.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_InventoryHome(object):
    def setupUi(self, InventoryHome):
        InventoryHome.setObjectName("InventoryHome")
        InventoryHome.resize(659, 450)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICONOI.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        InventoryHome.setWindowIcon(icon)
        InventoryHome.setAutoFillBackground(False)
        InventoryHome.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(4,155,180, 255), stop:1 rgba(125,216,87, 255));")
        self.centralwidget = QtWidgets.QWidget(InventoryHome)
        self.centralwidget.setObjectName("centralwidget")
        self.tittle = QtWidgets.QLabel(self.centralwidget)
        self.tittle.setGeometry(QtCore.QRect(140, 20, 381, 41))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittle.setFont(font)
        self.tittle.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"\n"
"")
        self.tittle.setObjectName("tittle")
        self.iProduct = QtWidgets.QLineEdit(self.centralwidget)
        self.iProduct.setGeometry(QtCore.QRect(170, 110, 181, 31))
        self.iProduct.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iProduct.setText("")
        self.iProduct.setObjectName("iProduct")
        self.eProduct = QtWidgets.QLabel(self.centralwidget)
        self.eProduct.setGeometry(QtCore.QRect(20, 110, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eProduct.setFont(font)
        self.eProduct.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eProduct.setObjectName("eProduct")
        self.eCant = QtWidgets.QLabel(self.centralwidget)
        self.eCant.setGeometry(QtCore.QRect(20, 190, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eCant.setFont(font)
        self.eCant.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eCant.setObjectName("eCant")
        self.eRef = QtWidgets.QLabel(self.centralwidget)
        self.eRef.setGeometry(QtCore.QRect(20, 150, 131, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eRef.setFont(font)
        self.eRef.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eRef.setObjectName("eRef")
        self.eUnit = QtWidgets.QLabel(self.centralwidget)
        self.eUnit.setGeometry(QtCore.QRect(20, 230, 141, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eUnit.setFont(font)
        self.eUnit.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eUnit.setObjectName("eUnit")
        self.eTotal = QtWidgets.QLabel(self.centralwidget)
        self.eTotal.setGeometry(QtCore.QRect(20, 270, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eTotal.setFont(font)
        self.eTotal.setStyleSheet("background-color: rgba(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 63 14pt \"Bahnschrift SemiBold\";\n"
"font: 18pt \"Tw Cen MT Condensed Extra Bold\";")
        self.eTotal.setObjectName("eTotal")
        self.iUnit = QtWidgets.QLineEdit(self.centralwidget)
        self.iUnit.setGeometry(QtCore.QRect(170, 230, 181, 31))
        self.iUnit.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iUnit.setText("")
        self.iUnit.setObjectName("iUnit")
        self.iTotal = QtWidgets.QLineEdit(self.centralwidget)
        self.iTotal.setGeometry(QtCore.QRect(170, 270, 181, 31))
        self.iTotal.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iTotal.setText("")
        self.iTotal.setReadOnly(True)
        self.iTotal.setObjectName("iTotal")
        self.addSell = QtWidgets.QPushButton(self.centralwidget)
        self.addSell.setGeometry(QtCore.QRect(160, 320, 211, 41))
        self.addSell.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addSell.setStyleSheet("background-color: rgb(73, 149, 66);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.addSell.setObjectName("addSell")
        self.reportDaily = QtWidgets.QPushButton(self.centralwidget)
        self.reportDaily.setGeometry(QtCore.QRect(400, 160, 191, 41))
        self.reportDaily.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reportDaily.setStyleSheet("background-color: rgb(58, 152, 132);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.reportDaily.setObjectName("reportDaily")
        self.reportGeneral = QtWidgets.QPushButton(self.centralwidget)
        self.reportGeneral.setGeometry(QtCore.QRect(400, 210, 211, 41))
        self.reportGeneral.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.reportGeneral.setStyleSheet("background-color: rgb(58, 152, 132);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.reportGeneral.setObjectName("reportGeneral")
        self.btnExit = QtWidgets.QPushButton(self.centralwidget)
        self.btnExit.setGeometry(QtCore.QRect(220, 370, 91, 41))
        self.btnExit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnExit.setStyleSheet("background-color: rgb(200, 15, 2);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnExit.setObjectName("btnExit")
        self.spinCant = QtWidgets.QSpinBox(self.centralwidget)
        self.spinCant.setGeometry(QtCore.QRect(170, 190, 181, 31))
        self.spinCant.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.spinCant.setObjectName("spinCant")
        self.eInformes = QtWidgets.QLabel(self.centralwidget)
        self.eInformes.setGeometry(QtCore.QRect(400, 110, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setUnderline(True)
        font.setWeight(10)
        self.eInformes.setFont(font)
        self.eInformes.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"text-decoration: underline;")
        self.eInformes.setObjectName("eInformes")
        self.addProductoVen = QtWidgets.QPushButton(self.centralwidget)
        self.addProductoVen.setGeometry(QtCore.QRect(400, 260, 231, 41))
        self.addProductoVen.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addProductoVen.setStyleSheet("background-color: rgb(99, 38, 140);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.addProductoVen.setObjectName("addProductoVen")
        self.iRef = QtWidgets.QComboBox(self.centralwidget)
        self.iRef.setGeometry(QtCore.QRect(170, 150, 181, 31))
        self.iRef.setStyleSheet("background-color: rgb(225, 225, 225);\n"
"font: 12pt \"Arial\";\n"
"border-radius: 12px;")
        self.iRef.setObjectName("iRef")
        self.eAlerta = QtWidgets.QLabel(self.centralwidget)
        self.eAlerta.setGeometry(QtCore.QRect(280, 60, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.eAlerta.setFont(font)
        self.eAlerta.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"font: 12pt \"Arial\";\n"
"color: rgb(213, 0, 0);\n"
"border-radius:10px;")
        self.eAlerta.setObjectName("eAlerta")
        InventoryHome.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(InventoryHome)
        self.statusbar.setObjectName("statusbar")
        InventoryHome.setStatusBar(self.statusbar)

        self.retranslateUi(InventoryHome)
        QtCore.QMetaObject.connectSlotsByName(InventoryHome)

    def retranslateUi(self, InventoryHome):
        _translate = QtCore.QCoreApplication.translate
        InventoryHome.setWindowTitle(_translate("InventoryHome", "Registro de Ventas"))
        self.tittle.setText(_translate("InventoryHome", "REGISTRO DE VENTAS"))
        self.eProduct.setText(_translate("InventoryHome", "Producto:"))
        self.eCant.setText(_translate("InventoryHome", "Cantidad:"))
        self.eRef.setText(_translate("InventoryHome", "Referencia:"))
        self.eUnit.setText(_translate("InventoryHome", "Vr. Unitario:"))
        self.eTotal.setText(_translate("InventoryHome", "Vr. Total:"))
        self.addSell.setText(_translate("InventoryHome", "Agregar Venta"))
        self.reportDaily.setText(_translate("InventoryHome", "Informe Diario"))
        self.reportGeneral.setText(_translate("InventoryHome", "Informe General"))
        self.btnExit.setText(_translate("InventoryHome", "Salir"))
        self.eInformes.setText(_translate("InventoryHome", "INFORMES"))
        self.addProductoVen.setText(_translate("InventoryHome", "Agregar Producto"))
        self.eAlerta.setText(_translate("InventoryHome", "  Alerta"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    InventoryHome = QtWidgets.QMainWindow()
    ui = Ui_InventoryHome()
    ui.setupUi(InventoryHome)
    InventoryHome.show()
    sys.exit(app.exec_())
