# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Inventario.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ReportDaily(object):
    def setupUi(self, ReportDaily):
        ReportDaily.setObjectName("ReportDaily")
        ReportDaily.resize(659, 463)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICONOI.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReportDaily.setWindowIcon(icon)
        ReportDaily.setAutoFillBackground(False)
        ReportDaily.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(4,155,180, 255), stop:1 rgba(125,216,87, 255));")
        self.centralwidget = QtWidgets.QWidget(ReportDaily)
        self.centralwidget.setObjectName("centralwidget")
        self.tittleDi = QtWidgets.QLabel(self.centralwidget)
        self.tittleDi.setGeometry(QtCore.QRect(80, 30, 491, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittleDi.setFont(font)
        self.tittleDi.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"")
        self.tittleDi.setObjectName("tittleDi")
        self.btnBackDi = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackDi.setGeometry(QtCore.QRect(20, 390, 91, 41))
        self.btnBackDi.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBackDi.setStyleSheet("background-color: rgb(50, 185, 41);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnBackDi.setObjectName("btnBackDi")
        self.btnNext = QtWidgets.QPushButton(self.centralwidget)
        self.btnNext.setGeometry(QtCore.QRect(510, 390, 131, 41))
        self.btnNext.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNext.setStyleSheet("background-color: rgb(249, 167, 25);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnNext.setObjectName("btnNext")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 120, 531, 231))
        self.tableWidget.setStyleSheet("background-color: rgb(101, 200, 156);\n"
"\n"
"\n"
"background-color: rgb(215, 233, 255);\n"
"font: 14pt \"Arial\";\n"
"\n"
"")
        self.tableWidget.setRowCount(5)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        ReportDaily.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReportDaily)
        self.statusbar.setObjectName("statusbar")
        ReportDaily.setStatusBar(self.statusbar)

        self.retranslateUi(ReportDaily)
        QtCore.QMetaObject.connectSlotsByName(ReportDaily)

    def retranslateUi(self, ReportDaily):
        _translate = QtCore.QCoreApplication.translate
        ReportDaily.setWindowTitle(_translate("ReportDaily", "Informe Diario de Ventas"))
        self.tittleDi.setText(_translate("ReportDaily", "INFORME DIARIO DE VENTAS"))
        self.btnBackDi.setText(_translate("ReportDaily", "Atrás"))
        self.btnNext.setText(_translate("ReportDaily", "Siguiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportDaily = QtWidgets.QMainWindow()
    ui = Ui_ReportDaily()
    ui.setupUi(ReportDaily)
    ReportDaily.show()
    sys.exit(app.exec_())

