# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ReportGeneral.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReportGeneral(object):
    def setupUi(self, ReportGeneral):
        ReportGeneral.setObjectName("ReportGeneral")
        ReportGeneral.resize(659, 463)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ICONOI.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ReportGeneral.setWindowIcon(icon)
        ReportGeneral.setAutoFillBackground(False)
        ReportGeneral.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(4,155,180, 255), stop:1 rgba(125,216,87, 255));")
        self.centralwidget = QtWidgets.QWidget(ReportGeneral)
        self.centralwidget.setObjectName("centralwidget")
        self.tittleGe = QtWidgets.QLabel(self.centralwidget)
        self.tittleGe.setGeometry(QtCore.QRect(60, 30, 531, 31))
        font = QtGui.QFont()
        font.setFamily("Arial Black")
        font.setPointSize(18)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(10)
        self.tittleGe.setFont(font)
        self.tittleGe.setStyleSheet("background-color: rgb(255, 255, 255, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 87 18pt \"Arial Black\";\n"
"")
        self.tittleGe.setObjectName("tittleGe")
        self.btnBackGe = QtWidgets.QPushButton(self.centralwidget)
        self.btnBackGe.setGeometry(QtCore.QRect(20, 390, 91, 41))
        self.btnBackGe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnBackGe.setStyleSheet("background-color: rgb(50, 185, 41);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnBackGe.setObjectName("btnBackGe")
        self.btnNextGe = QtWidgets.QPushButton(self.centralwidget)
        self.btnNextGe.setGeometry(QtCore.QRect(510, 390, 141, 41))
        self.btnNextGe.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnNextGe.setStyleSheet("background-color: rgb(0, 151, 178);\n"
"background-color: rgb(249, 167, 25);\n"
"color: rgb(255, 255, 255);\n"
"border-radius:15px;\n"
"font: 87 14pt \"Arial Black\";")
        self.btnNextGe.setObjectName("btnNextGe")
        self.tableWidgetGe = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidgetGe.setGeometry(QtCore.QRect(60, 110, 531, 231))
        self.tableWidgetGe.setStyleSheet("background-color: rgb(101, 200, 156);\n"
"\n"
"\n"
"background-color: rgb(215, 233, 255);\n"
"font: 14pt \"Arial\";\n"
"\n"
"")
        self.tableWidgetGe.setRowCount(5)
        self.tableWidgetGe.setColumnCount(4)
        self.tableWidgetGe.setObjectName("tableWidgetGe")
        self.tableWidgetGe.horizontalHeader().setCascadingSectionResizes(False)
        ReportGeneral.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ReportGeneral)
        self.statusbar.setObjectName("statusbar")
        ReportGeneral.setStatusBar(self.statusbar)

        self.retranslateUi(ReportGeneral)
        QtCore.QMetaObject.connectSlotsByName(ReportGeneral)

    def retranslateUi(self, ReportGeneral):
        _translate = QtCore.QCoreApplication.translate
        ReportGeneral.setWindowTitle(_translate("ReportGeneral", "Informe General de Ventas"))
        self.tittleGe.setText(_translate("ReportGeneral", "INFORME GENERAL DE VENTAS"))
        self.btnBackGe.setText(_translate("ReportGeneral", "Atrás"))
        self.btnNextGe.setText(_translate("ReportGeneral", "Siguiente"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReportGeneral = QtWidgets.QMainWindow()
    ui = Ui_ReportGeneral()
    ui.setupUi(ReportGeneral)
    ReportGeneral.show()
    sys.exit(app.exec_())
